In [1]:
import pandas as pd
from pathlib import Path
%matplotlib inline

In [2]:
#Import commodity prices into dataframe from CSV
commodity_price_df = pd.read_csv(
    Path('../../data/rawdata/commodity_prices.csv'),
    parse_dates=True,
    infer_datetime_format=True
)

commodity_price_df['Date'] = pd.to_datetime(commodity_price_df['Date'])
commodity_price_df['Date'] = commodity_price_df['Date'].apply(lambda x: x.strftime('%Y-%m-%d'))
commodity_price_df.rename(columns = {'Date':'time'}, inplace=True)

commodity_price_df = commodity_price_df.set_index('time')

#Check dataframe and data types

display(commodity_price_df.head())
commodity_price_df.dtypes

              oil  gasoline  diesel    ng     gold  silver
time
2020-11-02  36.60     1.052   1.113  3.03  1889.90  23.975
2020-11-03  37.44     1.077   1.132  2.88  1908.30  24.170
2020-11-04  38.97     1.108   1.167  2.63  1900.15  23.975
2020-11-05  38.56     1.116   1.162  2.69  1938.45  24.570
2020-11-06  36.97     1.084   1.145  2.67  1940.80  25.780

oil         float64
gasoline    float64
diesel      float64
ng          float64
gold        float64
silver      float64
dtype: object

In [3]:
commodity_daily_returns = commodity_price_df.pct_change().dropna()

In [4]:
commodity_daily_returns.head()

                 oil  gasoline    diesel        ng      gold    silver
time
2020-11-03  0.022951  0.023764  0.017071 -0.049505  0.009736  0.008133
2020-11-04  0.040865  0.028784  0.030919 -0.086806 -0.004271 -0.008068
2020-11-05 -0.010521  0.007220 -0.004284  0.022814  0.020156  0.024818
2020-11-06 -0.041234 -0.028674 -0.014630 -0.007435  0.001212  0.049247
2020-11-09  0.083311  0.071033  0.059389 -0.014981 -0.037871 -0.026183

In [5]:
equity_price_df = pd.read_csv(
    Path('../../data/rawdata/equity_prices.csv'),
    parse_dates=True, 
    infer_datetime_format=True
)


#Check dataframe and data types

display(equity_price_df.head())
equity_price_df.dtypes

equity_price_df['time'] = pd.to_datetime(equity_price_df['time'])

,time,AAPL,MSFT,GOOG,GOOGL,AMZN,TSLA,FB,NVDA,TSM,...,DOV,ON,KMX,MPWR,RCI,TEF,ET,GWW,VIACA,EIX
0,2020-11-02 00:00:00-05:00,108.770,202.32,1625.44,1623.17,3004.48,400.51,261.480,503.37,85.710,...,114.86,24.38,89.08,315.83,41.11,3.40,5.160,363.24,30.7900,57.56
1,2020-11-03 00:00:00-05:00,110.375,206.12,1649.28,1643.49,3046.25,423.74,265.080,520.79,87.695,...,117.12,25.05,93.12,314.40,41.27,3.43,5.500,371.18,31.2900,58.41
2,2020-11-04 00:00:00-05:00,114.940,216.32,1749.14,1747.04,3241.16,420.91,287.450,551.78,89.450,...,114.07,25.89,91.55,334.91,41.98,3.39,5.350,374.74,30.9900,57.47
3,2020-11-05 00:00:00-05:00,118.990,223.29,1764.48,1762.61,3322.00,438.09,294.715,566.41,90.430,...,117.37,26.44,93.34,357.23,42.62,3.45,5.355,378.96,32.3543,59.37
4,2020-11-06 00:00:00-05:00,118.685,223.62,1762.24,1759.40,3310.41,429.92,293.410,582.59,91.370,...,116.43,26.58,92.70,356.59,42.44,3.36,5.110,390.64,30.4000,58.32

In [6]:
equity_price_df['time'] = equity_price_df['time'].apply(lambda x: x.strftime('%Y-%m-%d'))

In [7]:
equity_price_df = equity_price_df.set_index('time')

In [8]:
equity_price_df.head()

,AAPL,MSFT,GOOG,GOOGL,AMZN,TSLA,FB,NVDA,TSM,JPM,...,DOV,ON,KMX,MPWR,RCI,TEF,ET,GWW,VIACA,EIX
time,,,,,,,,,,,,,,,,,,,,,
2020-11-02,108.770,202.32,1625.44,1623.17,3004.48,400.51,261.480,503.37,85.710,100.24,...,114.86,24.38,89.08,315.83,41.11,3.40,5.160,363.24,30.7900,57.56
2020-11-03,110.375,206.12,1649.28,1643.49,3046.25,423.74,265.080,520.79,87.695,103.38,...,117.12,25.05,93.12,314.40,41.27,3.43,5.500,371.18,31.2900,58.41
2020-11-04,114.940,216.32,1749.14,1747.04,3241.16,420.91,287.450,551.78,89.450,100.22,...,114.07,25.89,91.55,334.91,41.98,3.39,5.350,374.74,30.9900,57.47
2020-11-05,118.990,223.29,1764.48,1762.61,3322.00,438.09,294.715,566.41,90.430,104.35,...,117.37,26.44,93.34,357.23,42.62,3.45,5.355,378.96,32.3543,59.37
2020-11-06,118.685,223.62,1762.24,1759.40,3310.41,429.92,293.410,582.59,91.370,103.00,...,116.43,26.58,92.70,356.59,42.44,3.36,5.110,390.64,30.4000,58.32

In [9]:
#Determine if any columns are missing large amounts of data, such as new IPO
equity_price_df.isnull().sum().sort_values().tail(20)

BIIB      1
PCAR      1
DASH     26
ABNB     27
AFRM     49
STLA     52
FERG     85
RBLX     87
CPNG     88
SONY    103
COIN    111
APP     112
PATH    116
TTE     152
DIDI    165
LCID    182
HOOD    185
DNA     220
TOST    223
GFS     249
dtype: int64

In [10]:
#Remove columns with missing information, likely new IPO's
equity_price_df = equity_price_df.dropna(axis=1)
equity_price_df.isnull().sum().sort_values()

AAPL    0
FRC     0
GPN     0
IFF     0
NTR     0
       ..
HCA     0
ZM      0
CCI     0
MCO     0
EIX     0
Length: 479, dtype: int64

In [11]:
equity_daily_returns = equity_price_df.pct_change().dropna()
display(equity_daily_returns.head())
display(equity_daily_returns.tail())

,AAPL,MSFT,GOOG,GOOGL,AMZN,TSLA,FB,NVDA,TSM,JPM,...,DOV,ON,KMX,MPWR,RCI,TEF,ET,GWW,VIACA,EIX
time,,,,,,,,,,,,,,,,,,,,,
2020-11-03,0.014756,0.018782,0.014667,0.012519,0.013903,0.058001,0.013768,0.034607,0.023159,0.031325,...,0.019676,0.027482,0.045352,-0.004528,0.003892,0.008824,0.065891,0.021859,0.016239,0.014767
2020-11-04,0.041359,0.049486,0.060548,0.063006,0.063984,-0.006679,0.084390,0.059506,0.020013,-0.030567,...,-0.026042,0.033533,-0.016860,0.065235,0.017204,-0.011662,-0.027273,0.009591,-0.009588,-0.016093
2020-11-05,0.035236,0.032221,0.008770,0.008912,0.024942,0.040816,0.025274,0.026514,0.010956,0.041209,...,0.028930,0.021244,0.019552,0.066645,0.015245,0.017699,0.000935,0.011261,0.044024,0.033061
2020-11-06,-0.002563,0.001478,-0.001269,-0.001821,-0.003489,-0.018649,-0.004428,0.028566,0.010395,-0.012937,...,-0.008009,0.005295,-0.006857,-0.001792,-0.004223,-0.026087,-0.045752,0.030821,-0.060403,-0.017686
2020-11-09,-0.019927,-0.023611,-0.000715,0.000386,-0.051072,-0.019841,-0.050544,-0.063818,-0.025610,0.135728,...,0.028343,0.036117,0.035275,-0.111865,0.032045,0.125000,0.095890,-0.006041,0.007895,0.041838

,AAPL,MSFT,GOOG,GOOGL,AMZN,TSLA,FB,NVDA,TSM,JPM,...,DOV,ON,KMX,MPWR,RCI,TEF,ET,GWW,VIACA,EIX
time,,,,,,,,,,,,,,,,,,,,,
2021-11-03,0.009933,0.002160,0.006578,0.008135,0.021378,0.035703,0.010649,0.007309,-0.001227,0.000352,...,-0.008225,0.012948,0.021671,0.006771,0.013556,0.009195,-0.013211,0.007835,0.007748,-0.011646
2021-11-04,-0.003499,0.007426,0.012675,0.011736,0.027494,0.013218,0.012918,0.120540,0.033693,-0.013251,...,0.012411,0.034376,0.023313,-0.009005,0.004807,-0.037585,-0.049434,0.010724,-0.034722,0.004140
2021-11-05,0.001855,-0.001040,0.003568,0.003449,0.011389,-0.006741,0.015328,-0.001275,-0.000085,-0.001367,...,-0.004009,-0.012859,0.024437,0.022959,-0.014975,0.031953,0.007584,-0.014321,0.001670,0.015541
2021-11-08,-0.005223,0.002440,0.000975,0.001204,-0.008175,-0.048067,-0.007622,0.034907,0.026401,0.006129,...,0.012775,-0.006429,-0.004654,0.002157,0.030405,-0.002294,0.007527,0.004653,-0.012441,0.000312
2021-11-09,0.001728,-0.006559,-0.005420,-0.006008,0.027266,-0.113354,-0.008788,-0.020169,0.003474,-0.014127,...,0.003225,-0.018304,0.000909,-0.012994,0.010656,0.018391,-0.023479,0.011199,-0.010909,0.009913

In [12]:
oil_correlation_df = pd.DataFrame()

oil_correlation_df = pd.concat([commodity_daily_returns['oil'], equity_daily_returns], axis='columns', join='inner')
oil_correlation_df.isnull().sum()

oil      0
AAPL     0
MSFT     0
GOOG     0
GOOGL    0
        ..
TEF      0
ET       0
GWW      0
VIACA    0
EIX      0
Length: 480, dtype: int64

In [13]:
oil_correlation_df = oil_correlation_df.corr(method='pearson')

In [14]:
oil_correlation_df = oil_correlation_df.loc['oil']

In [15]:
oil_correlation_df = oil_correlation_df.sort_values(ascending=False)
display(oil_correlation_df.head())
display(oil_correlation_df.tail())

oil    1.000000
COP    0.641948
CNQ    0.639246
HES    0.637822
CVE    0.637175
Name: oil, dtype: float64

DLR    -0.155720
ABT    -0.155906
WEC    -0.158151
TMO    -0.179750
EQIX   -0.207716
Name: oil, dtype: float64

In [16]:
gasoline_correlation_df = pd.DataFrame()

gasoline_correlation_df = pd.concat([commodity_daily_returns['gasoline'], equity_daily_returns], axis='columns', join='inner')
gasoline_correlation_df = gasoline_correlation_df.corr(method='pearson')
gasoline_correlation_df = gasoline_correlation_df.loc['gasoline']
gasoline_correlation_df = gasoline_correlation_df.sort_values(ascending=False)

In [17]:
display(gasoline_correlation_df.head())
display(gasoline_correlation_df.tail())

gasoline    1.000000
COP         0.573990
CNQ         0.564912
DVN         0.559566
XOM         0.558627
Name: gasoline, dtype: float64

SBAC   -0.190984
CCI    -0.191076
GIS    -0.217488
DLR    -0.227956
EQIX   -0.231892
Name: gasoline, dtype: float64

In [18]:
diesel_correlation_df = pd.DataFrame()
ng_correlation_df = pd.DataFrame()
gold_correlation_df = pd.DataFrame()
silver_correlation_df = pd.DataFrame()

In [19]:
diesel_correlation_df = pd.concat([commodity_daily_returns['diesel'], equity_daily_returns], axis='columns', join='inner')
diesel_correlation_df = diesel_correlation_df.corr(method='pearson')
diesel_correlation_df = diesel_correlation_df.loc['diesel']
diesel_correlation_df = diesel_correlation_df.sort_values(ascending=False)

In [20]:
display(diesel_correlation_df.head())
display(diesel_correlation_df.tail())

diesel    1.000000
CVE       0.605623
CNQ       0.601313
COP       0.598624
SU        0.598181
Name: diesel, dtype: float64

DLR    -0.156041
ABT    -0.171981
TMO    -0.173486
EQIX   -0.186156
WEC    -0.190291
Name: diesel, dtype: float64

In [21]:
ng_correlation_df = pd.concat([commodity_daily_returns['ng'], equity_daily_returns], axis='columns', join='inner')
ng_correlation_df = ng_correlation_df.corr(method='pearson')
ng_correlation_df = ng_correlation_df.loc['ng']
ng_correlation_df = ng_correlation_df.sort_values(ascending=False)

In [22]:
display(ng_correlation_df.head())
display(ng_correlation_df.tail())

ng      1.000000
GNRC    0.219064
VZ      0.205138
WMT     0.201771
PBR     0.197399
Name: ng, dtype: float64

STZ    -0.115041
PAYC   -0.117017
ECL    -0.117325
OTIS   -0.121352
PLTR   -0.134558
Name: ng, dtype: float64

In [23]:
silver_correlation_df = pd.concat([commodity_daily_returns['silver'], equity_daily_returns], axis='columns', join='inner')
silver_correlation_df = silver_correlation_df.corr(method='pearson')
silver_correlation_df = silver_correlation_df.loc['silver']
silver_correlation_df = silver_correlation_df.sort_values(ascending=False)

In [24]:
display(silver_correlation_df.head())
display(silver_correlation_df.tail())

silver    1.000000
GOLD      0.309547
NEM       0.302297
FNV       0.275634
SCCO      0.251222
Name: silver, dtype: float64

CHTR   -0.108250
LHX    -0.118197
TSN    -0.132680
ROP    -0.136922
LLY    -0.147716
Name: silver, dtype: float64

In [25]:
gold_correlation_df = pd.concat([commodity_daily_returns['gold'], equity_daily_returns], axis='columns', join='inner')
gold_correlation_df = gold_correlation_df.corr(method='pearson')
gold_correlation_df = gold_correlation_df.loc['gold']
gold_correlation_df = gold_correlation_df.sort_values(ascending=False)

In [26]:
display(gold_correlation_df.head())
display(gold_correlation_df.tail())

gold    1.000000
GOLD    0.605813
NEM     0.550734
FNV     0.460998
DLR     0.235427
Name: gold, dtype: float64

SCHW   -0.169224
ZBH    -0.169941
CCL    -0.172192
BBVA   -0.181770
CUK    -0.189202
Name: gold, dtype: float64

In [27]:
winners_oil = oil_correlation_df.head(10)
winners_oil

oil    1.000000
COP    0.641948
CNQ    0.639246
HES    0.637822
CVE    0.637175
SU     0.630558
OXY    0.620419
EOG    0.609848
XOM    0.608122
CVX    0.604280
Name: oil, dtype: float64

In [28]:
losers_oil = oil_correlation_df.tail(10)
losers_oil

SHW    -0.137653
COST   -0.138171
KR     -0.138290
NEE    -0.144793
GIS    -0.145427
DLR    -0.155720
ABT    -0.155906
WEC    -0.158151
TMO    -0.179750
EQIX   -0.207716
Name: oil, dtype: float64

In [59]:
combined_df = pd.concat([oil_correlation_df, gasoline_correlation_df, diesel_correlation_df, ng_correlation_df, gold_correlation_df, silver_correlation_df], axis='columns', join='inner')

In [60]:
csv_data = pd.DataFrame()
combined_df

           oil  gasoline    diesel        ng      gold    silver
COP   0.641948  0.573990  0.598624  0.011039 -0.075084 -0.001236
CNQ   0.639246  0.564912  0.601313  0.047338 -0.041431  0.039430
HES   0.637822  0.556035  0.591556 -0.028817 -0.065523  0.019488
CVE   0.637175  0.535304  0.605623  0.001800 -0.010437  0.099305
SU    0.630558  0.546934  0.598181  0.008068 -0.075840  0.022440
...        ...       ...       ...       ...       ...       ...
DLR  -0.155720 -0.227956 -0.156041 -0.080279  0.235427  0.149809
ABT  -0.155906 -0.163035 -0.171981  0.032737  0.129940  0.129782
WEC  -0.158151 -0.142302 -0.190291 -0.093525  0.048461  0.044709
TMO  -0.179750 -0.174041 -0.173486  0.038094  0.142917  0.116926
EQIX -0.207716 -0.231892 -0.186156 -0.068013  0.117682  0.100680

[479 rows x 6 columns]

In [90]:
filtered_data = combined_df[(combined_df['oil'] >= .5) |
                (combined_df['gasoline'] >= .5) |
                (combined_df['diesel'] >= .5 ) |
                (combined_df['gold'] >= .5) |
                (combined_df['silver'] >= .5)]

filtered_tickers = filtered_data.index.tolist()

filtered_data = pd.DataFrame({n: combined_df.T[col].nlargest(top_n).index.tolist()
                 for n, col in enumerate(filtered_data.T)}).T
filtered_data.index = filtered_tickers

csv_data = filtered_data.to_csv()
#closing_prices_df_csv_data = closing_prices_df.to_csv('rawdata/equity_prices.csv')

         0         1
COP    oil    diesel
CNQ    oil    diesel
HES    oil    diesel
CVE    oil    diesel
SU     oil    diesel
OXY    oil    diesel
EOG    oil    diesel
XOM    oil    diesel
CVX    oil  gasoline
DVN    oil    diesel
BP     oil    diesel
EQNR   oil    diesel
PXD    oil    diesel
SLB    oil    diesel
EC     oil    diesel
E      oil    diesel
PSX    oil    diesel
ENB    oil    diesel
MPC    oil    diesel
OKE    oil  gasoline
VLO    oil  gasoline
KMI    oil    diesel
PTR    oil    diesel
NEM   gold    silver
GOLD  gold    silver