In [1]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv
from pathlib import Path
import alpaca_trade_api as tradeapi

In [2]:
load_dotenv()

True

In [3]:
alpaca_api_key = os.getenv("ALPACA_API_KEY")
alpaca_secret_key = os.getenv("ALPACA_SECRET_KEY")

display(type(alpaca_api_key))
display(type(alpaca_secret_key))

str

str

In [4]:
alpaca = tradeapi.REST(
     alpaca_api_key,
    alpaca_secret_key,
    api_version="v2")

In [5]:
nasdaq_df = pd.read_csv(
    Path('rawdata/nasdaq_screener.csv')
)

In [6]:
nasdaq_df = nasdaq_df.sort_values(by=['Market Cap'], ascending=False)
nasdaq_df = nasdaq_df.reset_index(drop=True)

In [7]:
nasdaq_filtered_100 = nasdaq_df.iloc[:100]
nasdaq_filtered_200 = nasdaq_df.iloc[100:200]
nasdaq_filtered_300 = nasdaq_df.iloc[200:300]
nasdaq_filtered_400 = nasdaq_df.iloc[300:400]
nasdaq_filtered_500 = nasdaq_df.iloc[400:500]

In [8]:
tickers_100 = nasdaq_filtered_100['Symbol']
tickers_200 = nasdaq_filtered_200['Symbol']
tickers_300 = nasdaq_filtered_300['Symbol']
tickers_400 = nasdaq_filtered_400['Symbol']
tickers_500 = nasdaq_filtered_500['Symbol']

In [9]:
start_date = pd.Timestamp("2020-10-31", tz="America/New_York").isoformat()
end_date = pd.Timestamp("2021-11-30", tz="America/New_York").isoformat()
timeframe = "1D"
limit_rows = 1000

In [10]:
prices_df_100 = alpaca.get_barset(
    tickers_100,
    timeframe,
    start=start_date,
    end=end_date,
    limit=limit_rows
).df

prices_df_100

                             AAPL                                         \
                             open     high       low    close     volume
time
2020-11-02 00:00:00-05:00  109.11  110.680  107.3200  108.770  106260834
2020-11-03 00:00:00-05:00  109.66  111.470  108.7300  110.375   93660131
2020-11-04 00:00:00-05:00  114.14  115.590  112.3500  114.940  114505478
2020-11-05 00:00:00-05:00  117.99  119.620  116.8686  118.990  107993032
2020-11-06 00:00:00-05:00  118.32  119.200  116.1300  118.685   99225280
...                           ...      ...       ...      ...        ...
2021-11-03 00:00:00-04:00  150.37  151.970  149.8200  151.490   44064848
2021-11-04 00:00:00-04:00  151.62  152.430  150.6400  150.960   49782226
2021-11-05 00:00:00-04:00  151.81  152.200  150.0600  151.240   54619968
2021-11-08 00:00:00-05:00  151.40  151.570  150.1600  150.450   45449352
2021-11-09 00:00:00-05:00  150.19  151.428  150.0601  150.710   33656271

                              ABBV                                        ...  \
                              open      high       low   close    volume  ...
time                                                                      ...
2020-11-02 00:00:00-05:00   86.030   88.5401   86.0000   88.25  17403418  ...
2020-11-03 00:00:00-05:00   89.140   89.3850   87.4300   87.97  14519532  ...
2020-11-04 00:00:00-05:00   93.135   97.4900   92.6703   94.50  45357361  ...
2020-11-05 00:00:00-05:00   95.360   95.5200   93.0000   93.66  13357772  ...
2020-11-06 00:00:00-05:00   92.975   93.6500   91.7101   92.86  11544292  ...
...                            ...       ...       ...     ...       ...  ...
2021-11-03 00:00:00-04:00  116.530  117.6100  116.2400  117.57   4775010  ...
2021-11-04 00:00:00-04:00  117.570  117.7200  116.3300  117.06   3111009  ...
2021-11-05 00:00:00-04:00  116.730  117.3199  115.5000  117.18   3316901  ...
2021-11-08 00:00:00-05:00  117.060  117.4500  115.7800  116.00   3842797  ...
2021-11-09 00:00:00-05:00  116.520  116.5900  115.6888  115.99   1529367  ...

                              WMT                                       \
                             open     high       low   close    volume
time
2020-11-02 00:00:00-05:00  140.59  140.810  139.0300  140.41   8911225
2020-11-03 00:00:00-05:00  141.65  144.160  141.5700  142.74   9219580
2020-11-04 00:00:00-05:00  141.57  144.390  141.3361  142.00  10209225
2020-11-05 00:00:00-05:00  144.00  144.230  142.9400  143.46   8196480
2020-11-06 00:00:00-05:00  144.36  146.220  143.5500  145.78   9102844
...                           ...      ...       ...     ...       ...
2021-11-03 00:00:00-04:00  149.60  150.290  149.0300  150.19   3603828
2021-11-04 00:00:00-04:00  150.18  151.848  149.8300  151.28   4142644
2021-11-05 00:00:00-04:00  151.95  152.000  149.6150  150.23   4438954
2021-11-08 00:00:00-05:00  150.22  150.510  148.7300  149.27   4398697
2021-11-09 00:00:00-05:00  149.25  149.770  148.8650  149.39   2495895

                              XOM
                             open     high    low    close    volume
time
2020-11-02 00:00:00-05:00  33.140  34.4550  32.57  33.9900  69736292
2020-11-03 00:00:00-05:00  34.490  34.4900  33.13  33.4100  68137129
2020-11-04 00:00:00-05:00  33.270  34.1400  32.53  33.2332  64101394
2020-11-05 00:00:00-05:00  33.370  33.9200  33.14  33.1700  55778579
2020-11-06 00:00:00-05:00  33.100  33.6600  32.62  32.7900  56939549
...                           ...      ...    ...      ...       ...
2021-11-03 00:00:00-04:00  64.020  64.4500  63.66  63.9300  13916440
2021-11-04 00:00:00-04:00  64.675  64.8900  63.83  64.4200  15047956
2021-11-05 00:00:00-04:00  65.050  65.3254  64.56  65.0100  14251859
2021-11-08 00:00:00-05:00  65.550  66.3800  65.38  65.7300  15394431
2021-11-09 00:00:00-05:00  65.770  66.0100  65.31  65.9450   9843422

[258 rows x 500 columns]

In [11]:
prices_df_200 = alpaca.get_barset(
    tickers_200,
    timeframe,
    start=start_date,
    end=end_date,
    limit=limit_rows
).df

In [12]:
prices_df_300 = alpaca.get_barset(
    tickers_300,
    timeframe,
    start=start_date,
    end=end_date,
    limit=limit_rows
).df

In [13]:
prices_df_400 = alpaca.get_barset(
    tickers_400,
    timeframe,
    start=start_date,
    end=end_date,
    limit=limit_rows
).df

In [14]:
prices_df_500 = alpaca.get_barset(
    tickers_500,
    timeframe,
    start=start_date,
    end=end_date,
    limit=limit_rows
).df

In [15]:
equity_prices = pd.concat([prices_df_100, prices_df_200, prices_df_300, prices_df_400, prices_df_500])
equity_prices.head()

                              A                          AAPL          \
                          close high low open volume    close    high
time
2020-11-02 00:00:00-05:00   NaN  NaN NaN  NaN    NaN  108.770  110.68
2020-11-03 00:00:00-05:00   NaN  NaN NaN  NaN    NaN  110.375  111.47
2020-11-04 00:00:00-05:00   NaN  NaN NaN  NaN    NaN  114.940  115.59
2020-11-05 00:00:00-05:00   NaN  NaN NaN  NaN    NaN  118.990  119.62
2020-11-06 00:00:00-05:00   NaN  NaN NaN  NaN    NaN  118.685  119.20

                                                          ...    ZS           \
                                low    open       volume  ... close high low
time                                                      ...
2020-11-02 00:00:00-05:00  107.3200  109.11  106260834.0  ...   NaN  NaN NaN
2020-11-03 00:00:00-05:00  108.7300  109.66   93660131.0  ...   NaN  NaN NaN
2020-11-04 00:00:00-05:00  112.3500  114.14  114505478.0  ...   NaN  NaN NaN
2020-11-05 00:00:00-05:00  116.8686  117.99  107993032.0  ...   NaN  NaN NaN
2020-11-06 00:00:00-05:00  116.1300  118.32   99225280.0  ...   NaN  NaN NaN

                                        ZTS
                          open volume close high low open volume
time
2020-11-02 00:00:00-05:00  NaN    NaN   NaN  NaN NaN  NaN    NaN
2020-11-03 00:00:00-05:00  NaN    NaN   NaN  NaN NaN  NaN    NaN
2020-11-04 00:00:00-05:00  NaN    NaN   NaN  NaN NaN  NaN    NaN
2020-11-05 00:00:00-05:00  NaN    NaN   NaN  NaN NaN  NaN    NaN
2020-11-06 00:00:00-05:00  NaN    NaN   NaN  NaN NaN  NaN    NaN

[5 rows x 2500 columns]

In [16]:
closing_prices_df = pd.DataFrame()

In [26]:
for ticker in tickers_100:
    closing_prices_df[ticker] = prices_df_100[ticker]['close']

In [28]:
for ticker in tickers_200:
    closing_prices_df[ticker] = prices_df_200[ticker]['close']

In [30]:
for ticker in tickers_300:
    closing_prices_df[ticker] = prices_df_300[ticker]['close']

In [31]:
for ticker in tickers_400:
    closing_prices_df[ticker] = prices_df_400[ticker]['close']

In [32]:
for ticker in tickers_500:
    closing_prices_df[ticker] = prices_df_500[ticker]['close']

In [34]:
closing_prices_df.isnull().sum()

AAPL     0
MSFT     0
GOOG     0
GOOGL    0
AMZN     0
        ..
TEF      0
ET       0
GWW      0
VIACA    0
EIX      0
Length: 500, dtype: int64

In [36]:
closing_prices_df_csv_data = closing_prices_df.to_csv('rawdata/equity_prices.csv')